export const products = "products";
export const images = "images";
export const categories = "categories";
export const brands = "brands";
export const colors = "colors";
export const designs = "designs";
export const fabrics = "fabrics";
export const sexes = "sexes";
export const types = "types";
export const sizes = "sizes";
export const orders = "orders";
export const roles = "roles";
export const permissions = "permissions";
export const resources = "resources";
export const users = "user";
export const priceRange = "price-range";
export const product = (id) => `product-${id}`;
export const productImages = (productId) => `image-${productId}`;
export const productCategories = (productId) => `category-${productId}`;
export const order = (id) => `order-${id}`;
export const role = (id) => `role-${id}`;
export const permission = (id) => `permission-${id}`;
export const user = (id) => `user-${id}`;
